### ISSUE TITLE
More POIS

### ISSUE THREAD

**Issue by fawcett** [maptimemsp/nacis2015-map#106]
<strike>Betty Danger's Country Club
2501 Marshall St NE, Minneapolis, MN 55418
"Complete with a vertical patio (Ferris Wheel)!"
http://bettydangers.com/
-93.27138036489485,
          45.013337595055305</strike>

<strike>Psycho Suzi's Motor Lounge
http://psychosuzis.com/
1900 Marshall St NE, Minneapolis, MN 55418
-93.27238619327545,
          45.007483829528276\
          "Tiki, tattoos, and riverfront patio."</strike>

<strike>Maeve's Cafe
http://maeves.com/
300 13th Ave NE, Minneapolis, MN 55413
-93.26443076133727,
          45.00076842362267</strike>

<strike>Matchbox Coffee Shop
1306 2nd St NE
Minneapolis, MN 55413
-93.26632976531982,
          45.00125205018181
"Great coffee, cash only"</strike>

<strike>Sip Coffee Bar
http://sipcoffeebar.com/
34 13th Ave NE
Minneapolis, MN 55413
"Organic Fair Trade beans, food from scratch"
-93.27168345451354,
          44.99938010823233</strike>

<strike>Acadia Cafe
http://acadiapub.com/
'bar'
329 Cedar Avenue
Minneapolis, MN 55454
-93.24707686901093,
          44.97029361791892</strike>

<strike>The Bachelor Farmer
50 N 2nd Ave
Minneapolis, MN 55401
http://thebachelorfarmer.com
"Quintesential MN restaurant, Nordic cuisine, POTUS ate here when he was in town."
-93.26885640621185,
          44.98571326886948</strike>

**Comment by kcantner** [comment]
I've added The Bachelor Farmer!

**Comment by fawcett** [comment]
Kitty added Matchbox Cafe

**Comment by geospatialem** [comment]
@fawcett: Maybe we can cross off the one's that have been added?

**Comment by geospatialem** [comment]
@fawcett I say since you already gathered the intel on these POI's you should be the guru who gets to add the last two in. What say you?

**Comment by fawcett** [comment]
I say PULL!

**Comment by geospatialem** [comment]
:laughing: ... :heart: it!
