### ISSUE TITLE
Please delete this point...

### ISSUE THREAD

**Issue by emande14** [maptimemsp/nacis2015-map#121]
As of August 31st there is no Dogwood Coffee Bar located at 228 N Washington Ave, Minneapolis, MN 55401. Could someone please remove this point? I know this because I work for Dogwood ;)

Thanks!

Eddie

**Comment by geospatialem** [comment]
Thanks @emande14 for the tip! 

Can you elaborate more on this issue? Is there a Dogwood Coffee Bar located elsewhere in Minneapolis that we can move the point to?

**Comment by emande14** [comment]
Certainly. The coffee bar at 3001 Hennepin Ave (Calhoun Square) has already been mapped, though there is another Dogwood Coffee Bar located at 4021 East Lake Street, Minneapolis, MN 55406 that has not yet been mapped.

**Comment by fawcett** [comment]
Thanks for the intel Eddie, the power of the crowd!  I was the one who had originally mapped it based on info from the Dogwood site.  I love Dogwood and think that it is some of the best in the city.
