### ISSUE TITLE
Commit not showing on map

### ISSUE THREAD

**Issue by geospatialem** [maptimemsp/nacis2015-map#23]
It looks like the [latest pull request](https://github.com/MaptimeMSP/nacis2015-map/pull/22) isn't showing up on the map after merging both the <code>master</code> and <code>gh-pages</code> branches.

The map should have added a point for **Sun Street Breads** in south Minneapolis, like so:
![capture](https://cloud.githubusercontent.com/assets/5023024/8896535/4e702366-33c5-11e5-89ee-7a51fc0e2197.JPG)

The GeoJSON has been updated, and has no errors, but isn't showing up. Do you know why this is?

**Comment by fawcett** [comment]
The data was good, but the display code had a bug.  

Fixed in this commit:  https://github.com/MaptimeMSP/nacis2015-map/commit/229b62ad31ff22ed5dd086adad53f6a3ba4351ed

**Comment by geospatialem** [comment]
Awesome, thanks @fawcett! :+1:
