### ISSUE TITLE
What are my options for poi_type?

### ISSUE THREAD

**Issue by mtaylorlong** [maptimemsp/nacis2015-map#3]
I'm sure this is somewhere in the Wiki, but can anyone point me to where I can learn what my options are for poi_types? The examples used "conf" as the conference location and "bar" for Marvel bar. What else is there?

**Comment by geospatialem** [comment]
Great question, @mtaylorlong! :+1: 

Currently, the POI's can be listed under the following types:
- conf
- restaurant
- cafe
- bar
- beer 

However, anyone can edit the [script.js](https://raw.githubusercontent.com/MaptimeMSP/nacis2015-map/master/js/script.js) file to add in additional options as we expand the map. For the latest POI options, you can check the Wiki site under the [data notes](https://github.com/MaptimeMSP/nacis2015-map/wiki/data-notes#current-categories-for-pois) page. :smiley_cat:

**Comment by geospatialem** [comment]
Closing this issue, but anyone can view it in the closed issues, and the information can be seen on the Wiki site. :sunglasses:
