### ISSUE TITLE
Github and firewall issue? 

### ISSUE THREAD

**Issue by marillenkrapfen** [maptimemsp/nacis2015-map#32]
OK, here's my newbie question: got to the point of creating my local repository. Got this error:

fatal:unable to access 'https://github.com/marillenkrapfen/nacis2015-map.git/': error: 140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

Is there any way I can change my configuration to allow this to work?

Thanks for the help.

**Comment by fawcett** [comment]
I haven't seen this one before.  

Can you provide some more information to help diagnose it?

What operating system are you on?  Are you using Git on the commandline or in a GUI client?

What operation were you doing when you got this message?  

I did verify the URL that you are using, and it is correct.  This error is usually due to outdated SSL libraries on your computer, or incompatible versions between those on your computer and the ones on the server.

**Comment by marillenkrapfen** [comment]
Thanks -- I have Windows 7 and have just followed the basic steps outlined in the project pages -- installed Git, used command line (Git Bash) to configure with my user name and email, then used git clone with my url to run the clone to my local machine. This is what runs into the error. I have attempted the cloning using the little GUI tool and it generates the same error. I have attempted to create the local repository in a couple of different places on my C:/ drive and got the same result. I see there is an ssl folder in the git install but I have not changed anything there. All the files are the most recent ones that came with the latest Git install.

Thanks for any thoughts.

**Comment by geospatialem** [comment]
@marillenkrapfen - Are you by chance using any of this on a closed network (or work machine)? 

A [resolution](http://w3facility.org/question/git-pull-fatal-unable-to-access-error140770fcssl-routines-ssl23_get_server_hello-uknown-protocol) I happened upon says the following:

> Turns out my company’s network suddenly blocked the IP and port number, thus not allowing me to access it. So, be sure to ping it from whatever network you’re on if you receive a similar issue.

**Comment by marillenkrapfen** [comment]
Yes, I am and it is probable that there is a firewall issue -- I was hoping there might be a way to pass in the url or configure some sort of permissions file to get around the blockage. I just don't know where to begin with that, though, if it is possible.

**Comment by geospatialem** [comment]
@marillenkrapfen: Were you able to diagnose the problem?

**Comment by marillenkrapfen** [comment]
No, I tried assigning a different port using the git bash console and that didn't work. I'm sure it is a firewall/proxy issue because my work environment pretty much completely blocks the outside world, but I was too busy with other work and I gave up. Thanks for asking -- if I ever hear of a way around this I will let you know.

**Comment by marillenkrapfen** [comment]
Hey, got it -- you inspired me to try again and I found the right way to configure the proxy. I used this format:

git config --global http.proxy http://mydomain\myusername:mypassword@myproxyserver:8080

Then tried git clone again, and it worked. 

Here is the webpage that gave it to me:

http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy

Thanks to all for the input!

**Comment by geospatialem** [comment]
Hooray, that's great news! Thanks for sharing! :+1:

**Comment by geospatialem** [comment]
Closing since you were a :guitar::star2: and solved this!

**Comment by marillenkrapfen** [comment]
:blush: :grinning:
