### ISSUE TITLE
Add NiceRide Stations

### ISSUE THREAD

**Issue by geospatialem** [maptimemsp/nacis2015-map#49]
Find a service/shp/json file of points from the [Nice Ride Minnesota](https://secure.niceridemn.org/map) map! 

:bike:

**Comment by fawcett** [comment]
https://secure.niceridemn.org/data2/stations.json
I had an example on how to parse their json in one of my old Python workshops.  There is something funky about their timestamp, if I remember correctly.  I can look it up.

**Comment by geospatialem** [comment]
I saw that file, too. I wasn't sure if it would be useful, or even worth it to explore as it seems like its built for the Google Maps API, but I could be wrong. The lat/long's are stored as "la" and "lo" with all the other attributes, too. :dizzy_face:

In the meantime, I'll continue to look for other sources.

**Comment by geospatialem** [comment]
Found one here: https://raw.githubusercontent.com/dreyco676/NiceRideMN/master/Data/station_loc_master.csv. Will do some more verification, to ensure it matches up with what we see on the NiceRide website and add it in in the next few days. :smiley:

**Comment by geospatialem** [comment]
Add in the Nice Ride url into the popup (http://www.niceridemn.org).
