### ISSUE TITLE
Add the fun run & walk route to the map

### ISSUE THREAD

**Issue by geospatialem** [maptimemsp/nacis2015-map#50]
Add the fun run & walk route to the interactive map and link back to the [official map](http://schd.ws/hosted_files/nacis2015/ab/FunRun_forweb.png)!

![funrun_forweb](https://cloud.githubusercontent.com/assets/5023024/9090192/92535e40-3b5e-11e5-9f94-e58efa67d8e2.png)

**Comment by fawcett** [comment]
Since there is already a fun run map, I would vote for keeping it off of our map.  At least that is my first reaction.  Not a strong one though.

**Comment by geospatialem** [comment]
For those following along, @fawcett and I talked outside of GitHub and decided to try a feature branch named `fun-run-route-and-legend` to see how this plays out before commiting directly to the`master` branch.

So... I just pushed up commit 70bd1e4db0a1966e4713726b0cb62b6838d89c89 that adds a legend to the map with two layers to turn on/off: 
- LRT stations/lines, and 
- Nice Ride stations.

In addition, I'll try adding the fun run route in another commit (coming soon). :smiley_cat:

**Comment by geospatialem** [comment]
@fawcett: Thoughts? Enhancements? Leave it out? 

I'm open to any and all possibilities where you see fit.

**Comment by fawcett** [comment]
I am up for looking at it on the map with the layer control.  I also think that it might look just fine with everything all in the same 'layer'.  

If we were only doing a map for desktop/laptops, I wouldn't put much thought into adding the layer control.  My main concern is how it will work on a phone/mobile device.

**Comment by geospatialem** [comment]
Closing this, @fawcett and I had conversations outside of GitHub and talked about the effects. Additional editing may come into play later, but as of 8/11 the legend collapses on mobile devices and all layers load on load with the exception of the fun run layer.
