### ISSUE TITLE
Geolocator issue on iPhone

### ISSUE THREAD

**Issue by geospatialem** [maptimemsp/nacis2015-map#62]
While at a conference this past week I noticed the geolocator works for 15-20 seconds and then times out. Let's try and troubleshoot this to see if its related to the widget and/or if we can fix it.

**Comment by crpAnderson** [comment]
Happens on android as well. "geolocation error: User denied Geolocation" displayed in alert window when you press the locate me button.

**Comment by fawcett** [comment]
It works on my iPhone.  Do you have location services enabled?  When I hit the button, I get an alert asking whether I want to allow the web app to have access to my location.

**Comment by geospatialem** [comment]
@fawcett Leave the map open with the locator enabled for ~60 seconds and see if anything changes. My phone was fine for about a minute, and then it would eventually time out and give an error. Once I saw the error, it would show up sooner when I tried it later (even after restarting my phone).

**Comment by fawcett** [comment]
Will do.  If there is an issue with the code, it is the straight code from https://github.com/domoritz/leaflet-locatecontrol  I don't see issues that exactly match what you are seeing, but here are the issues:  https://github.com/domoritz/leaflet-locatecontrol/issues

If we can replicate the issue, we should push it upstream.

**Comment by geospatialem** [comment]
Ah, could be [this one](https://github.com/domoritz/leaflet-locatecontrol/issues/108) since I was testing on my Chrome for iOS browser... I'll do some additional testing tonight.

**Comment by geospatialem** [comment]
After some testing on both wifi and LTE I am unable to replicate the issue I saw initially. However, I think the issue could be related to slow speeds. I'll do some additional testing where network speeds are slower to see if I can replicate the issue.

**Comment by geospatialem** [comment]
I'm not seeing the error anymore, and @crpAnderson's error seems to be related to the issue @fawcett mentions (location services). Closing for now, but I will reopen if I notice it again.

Thanks, all!
