### ISSUE TITLE
Add walking distances from venue using new MapBox Distance API

### ISSUE THREAD

**Issue by bitner** [maptimemsp/nacis2015-map#85]
https://www.mapbox.com/blog/distance-api/

**Comment by geospatialem** [comment]
While it looks awesome it appears to be in beta mode. I'm seeing the following message, _This API is a preview and may be changed or removed at any time_.

**Comment by geospatialem** [comment]
@bitner closing for now, but feel free to put in a PR if you get it working! :computer:
